meublog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('listcat/', views.CategoryListView.as_view(), name='listcat'),
    path('list/', views.CategoryIndListView.as_view(), name='list'),
    path('detailcat/<int:pk>', views.CategoryDetailView.as_view(), name='detailcat'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/' , views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
]

staticpages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    post_url = models.URLField(max_length=200, null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    content = models.CharField(max_length=5000)
    def __str__(self):
        return f'{self.title} ({self.created_at})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date_comment = models.DateTimeField(auto_now_add = True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)
    def __str__(self):
        return f'"{self.name}"'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'post_url',
            'content',
        ]
        labels = {
            'title': 'Título',
            'post_url': 'Post URL da Imagem',
            'content': 'Conteúdo:',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Headbanger',
            'text': 'Comentário',
        }

posts/views.py
from django import http
from django.db.models import fields
from django.http import HttpResponseRedirect
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Post
from .forms import PostForm, CommentForm
from django.views import generic

# Create your views here.
from django.http import HttpResponse
from .temp_data import post_data
from .models import Post, Comment, Category

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(title__icontains=search_term)
        context = {"post_list": post_list}    
    return render(request, 'posts/search.html', context)

class PostCreateView(generic.CreateView):
    model = Post
    fields = ['title', 'post_url', 'content']
    template_name = 'posts/create.html'

    def get_success_url(self):
        return reverse('posts:detail', kwargs={
            'pk': self.object.pk,
        })

class PostUpdateView(generic.UpdateView):
    model = Post
    fields = ['title', 'post_url', 'content']
    template_name = 'posts/update.html'

    def get_success_url(self):
        return reverse('posts:detail', kwargs={
            'pk': self.object.pk,
        })

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    
    def get_success_url(self):
        return reverse('posts:index')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/listcat.html'

class CategoryIndListView(generic.ListView):
    model = Category
    template_name = 'posts/list.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'posts/detailcat.html'

staticpages/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)

def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Postagem {{ post.title }} de ({{ post.created_at|date:"SHORT_DATE_FORMAT" }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página da postagem</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2> Criar Nova Postagem</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Deseja mesmo deletar a postagem "{{ post.title }} de ({{ post.created_at }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }} 
{% endblock title %}

{% block content %}
<h2>{{ post.title }}</h2>

<section class="dados-de-post">
    <img src="{{ post.post_url }}" alt="Imagem da Postagem {{ post.title}}">
    <ul>
        <li>{{ post.content }}</li>
        <p><li> Postado em {{ post.created_at }}</li></p>
        <li>Categoria: {{ post.category_set.all|join:"," }}</li>
        <li><a href="{% url 'posts:update' post.id %}">Editar</a> </li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a> </li>
    </ul>           
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>— {{ comment.author }} em {{ post.created_at|date:"SHORT_DATE_FORMAT" }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para esta postagem.</p>
        {% endif %}
    </ul>

    <hr>

    <a href="{% url 'posts:comment' post.pk %}"><button>Comentar</button></a>
</section>
{% endblock content %}

posts/templates/posts/detailcat.html
{% extends 'base.html' %}

{% block title %}
{{ category.name }} 
{% endblock title %}

{% block content %}
<h2>{{ category.name | safe }} </h2>
<p>{{ category.description | safe }} </p>
<section class="lista-de-posts">
    <ul>
        {% for post in category.posts.all %}
          <article class="post">
            <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.post_url }}"
               alt="Imagem da postagem {{ post.title}}"></a>
            <p><a href="{% url 'posts:detail' post.id %}">{{ post.title }} ({{ post.created_at|date:"SHORT_DATE_FORMAT" }})</a></p>
          </article>
        {% endfor %}
        
    </ul>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todas as Postagens</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Postagens</a></p>
    <p>Não encontrou o post? <a href="{% url 'posts:create' %}">Adicionar Nova Postagem</a></p>
</section>
{% if post_list %}
<section class="lista-de-posts">
    {% for post in post_list %}
    <article class="post">
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.post_url }}"
                alt="Imagem da postagem {{ post.title}}"></a>
        <p><a href="{% url 'posts:detail' post.id %}">{{ post.title }} ({{ post.created_at|date:"SHORT_DATE_FORMAT" }})</a></p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma postagem</p>
{% endif %}

{% endblock content %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block content %}
<h2>Todas as Categorias</h2>
{% if category_list %}
<section class="lista-de-posts">
    {% for category in category_list %}
    <article class="post">
        <div><p><h3><a href="{% url 'posts:detailcat' category.id %}">"{{ category.name }}"</a></h3></p></div>
        <div><p><a href="{% url 'posts:detailcat' category.id %}">"{{ category.description}}"</a></p></div>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma categoria.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/listcat.html
{% extends 'base.html' %}

{% block title %}
post por categoria
{% endblock title %}

{% block content %}
<h2>Postagens por categorias</h2>

<section>
    {% for category in category_list %}
        <hr>
        <article>
            <header>
                <h3>{{category.name}}</h3>
                <p><h4>{{category.description}}</h4></p>
            </header>
            <div class="lista-de-posts">
                {% for post in category.posts.all %}
                <div class="post">
                    <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.post_url }}"
                    alt="Imagem da postagem {{ post.title}}"></a>
                <p><a href="{% url 'posts:detail' post.id %}">{{ post.title }} ({{ post.created_at|date:"SHORT_DATE_FORMAT" }})</a></p>
                </div>
                {% endfor %}
            </div>
        </article>
    {% endfor %}

</section>
{% endblock content %}   
        

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por nome</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>

<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-posts">
    {% for post in post_list %}
    <article class="post">
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.post_url }}"
                alt="Imagem da postagem {{ post.title}}"></a>
        <p><a href="{% url 'posts:detail' post.id %}">{{ post.title }} ({{ post.created_at|date:"SHORT_DATE_FORMAT" }})</a></p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma postagem para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Postagem {{ post.title }} de ({{post.created_at}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    <p>
        <label for="id_title">Title</label>
        <input type="text" name="title" id="id_title" value="{{ post.title }}" />
    </p>
    <p>
        <label for="id_content">Content</label>
        <input type="text" name="content" id="id_content" value="{{ post.content }}"/>
    </p>
    <p>
        <label for="id_post_url">Post URL</label>
        <input type="url" name="post_url" id="id_post_url" value="{{ post.post_url }}" />
    </p>
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}{% endblock %} | Metal Brasil
        </title>
        <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>

    <body>
        <header id="cabecalho-principal">
            <a href="{% url 'index' %}"> <img src="{% static 'logo.jpeg' %}"></a>
            <h2>Metal Brasil</h2>
            <nav id="navegacao-principal">
                <ul>
                    <li><a href="{% url 'posts:index' %}">Posts</a></li>
                    <li><a href="{% url 'posts:listcat' %}">Posts por Categorias</a></li>
                    <li><a href="{% url 'posts:list' %}">Lista de Categorias</a></li>
                    <li><a href="{% url 'about'%}">Sobre</a></li>
                </ul>
            </nav>
        </header>
        <main id="conteiner-principal">
            {% block content %}
            {% endblock content %}
        </main>
        <footer id="rodape-principal">
            <p>
                <small>Victor Reiner 12412197</small>
            </p>
        </footer>
    </body>
</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Este blog foi criado para avaliação da disciplina PMR3304 - Sistemas de Informação</h2>
<p>Aluno: Victor Hugo Reiner Carvalho NUSP: 12412197</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página inicial
{% endblock title %}

{% block content %}
<h1><i>Metal Brasil</i></h1>
<p>Resenhando o metal nacional</p>
{% endblock content %}